services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      # Configure backend URL for API calls
      REACT_APP_BACKEND_URL: http://localhost:5000
      # Allow hot reloading in development
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  app-network:
    external: true
