services:
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SingleDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_backup_pg15_fixed.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      DB: SingleDatabase
      USER: admin
      PASSWORD: admin
      HOST: database
      DIALECT: postgres
      PORT: 5432
      HTTP_PORT: 5000
      secret: dev_secret_key_change_later
      EMAIL: dev@example.com
      EMAIL_PASSWORD: dev_email_password
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  uipanel:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    external: true

