services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SingleDatabase

  uipanel:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"

