version: "3.8"

services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SingleDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_backup_pg15_fixed_utf8.sql:/docker-entrypoint-initdb.d/init.sql:ro

  uipanel:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  postgres_data:
